### ISSUE TITLE
2023 Roadmap

### ISSUE THREAD

**Issue by giangndm** [8xFF/atm0s-sdn#80]
Monitor
- [ ] Dashboard
- [ ] Prometheus endpoint
- [ ] System metrics
- [ ] Node metrics
- [ ] Routing table metrics

Protocol:

- [ ] scoped routing
- [ ] public/private node-id
- [ ] nat-traversal
- [ ] encryption

Services:

- [ ] Key-value scoped value
- [ ] Key-value replication
- [ ] Manual discovery with node-types (scoped or global)
- [ ] DHT discovery
